### ISSUE TITLE
Mouse wheel stops working with v0.8.2

### ISSUE THREAD

**Issue by markk** [xremap/xremap#260]
After upgrading to v0.8.2 my mouse wheel doesn't work, presumably due to 2603e89999a25f6d65d2bce388ddb6f387101416. Is this intentional and/or workaroundable? 

This is using sway (--features sway).

**Comment by k0kubun** [comment]
Kind of intentional, but I intend to fix it shortly.

Do you use Arch Linux? If you don't, you should have no problem with using 0.8.1 in the meantime.

**Comment by markk** [comment]
Cool, thanks. No, Fedora.

**Comment by KeenS** [comment]
ping
I'm still using v0.8.1 because of this issue

**Comment by k0kubun** [comment]
Let's enable `REL_WHEEL` and `REL_HWHEEL` by default (whether `--mouse` or not), add a top-level configuration to disable `REL_WHEEL` and `REL_HWHEEL` (e.g. `enable_wheel: false`, default: true) for newer systemd users, and release it as v0.9.0.

Could anyone interested in that feature work on a pull request?
