### ISSUE TITLE
Recommended way to disable a key sequence?

### ISSUE THREAD

**Issue by hab25** [xremap/xremap#297]
It's probably worth mentioning the answer to this question in the README.

Note:
I'm currently achieving this by using the [reserved key](https://github.com/emberian/evdev/blob/1d020f11b283b0648427a2844b6b980f1a268221/src/scancodes.rs#LL25C6-L25C6).
The use case is to learn a new keymap faster when the key you want to disable should not be used for anything. For example: 

---
I want to start using `C-l` to close a google chrome tab, I don't want to use use `C-w` for anything, and currently, I'm using `C-w` to close a google chrome tab (this a google chrome default and cannot be disabled). I can do
```json
{
  "keymap": [
    {
      "application": {
        "only": "Google-chrome"
      },
      "exact_match": true,
      "remap": {
        "c-w": "reserved",
        "c-l": "c-w"
      }
    }
  ]
}
```
This way, `C-w` will start not doing anything which will help me break the habit of using it to close tabs. 

---
Q: Why not use two keybinds to do the same thing?
A: Spreading your habit among multiple keybinds weakens the muscle memory for any single keybind. Further, it makes the event that one of the keybinds is changed into some other command in the future easier to learn. More abstractly, one thing is generally simpler than multiple.

**Comment by k0kubun** [comment]
Nice tip. It might be too much for many users to see the entire context of this in README, but I think it's nice to mention `reserved` can be used for disabling a key and briefly explain why it could be useful. Would you be open to writing a pull request to make that change on README?

**Comment by hab25** [comment]
> Would you be open to writing a pull request to make that change on README?

Yes, after we reach an agreement here. 

One concern: `reserved` is not a no-op; applications could interpret it, and so it could have undesirable effects: 

---
As per [this comment in the Linux kernel repo](https://github.com/torvalds/linux/blob/7877cb91f1081754a1487c144d85dc0d2e2e7fc4/include/uapi/linux/input-event-codes.h#L67), 
>  Most of the keys/buttons are modeled after USB HUT 1.12 (see http://www.usb.org/developers/hidpage)

From https://www.usb.org/sites/default/files/documents/hut1_12v2.pdf:
> Reserved (no event indicated)⁹

> ⁹ Reserved for typical keyboard status of keyboard errors. Sent as a member of the keyboard array. Not a physical key.

---

So, wouldn't it be better if `xremap` implemented being able to specify `null` (which exists in JSON and (therefore) also in YAML 1.2) as the no-op, i.e. such that it can be used in place of how I'm currently using `reserved`?

I'm not sure how `xremap`, `evdev` and `uniput` work, but by "no-op" I mean something like: 

Intercepting from `evdev` the key event which was mapped to `null`, sending nothing to `uinput`.

**Comment by k0kubun** [comment]
That makes sense. I'd be open to merging a pull request that implements the `null` feature. In the meantime, using `reserved` could be a quick alternative.
