### ISSUE TITLE
KDE Wayland cannot connect to kwin script

### ISSUE THREAD

**Issue by dawsonalex** [xremap/xremap#445]
My system info:

```
Operating System: openSUSE Tumbleweed 20240321
KDE Plasma Version: 6.0.2
KDE Frameworks Version: 6.0.0
Qt Version: 6.6.2
Kernel Version: 6.8.1-1-default (64-bit)
Graphics Platform: Wayland
```

---

I've been following #433 thinking that was the cause of the issue I'm having but it's not. 'Modmaps' are working perfectly fine, but 'keymaps' don't do anything. Config to reproduce this is:

```
keypress_delay_ms: 10
modmap:
  - name: Make Ctrl act as ⌘ act
    remap:
      LeftCtrl: LeftAlt
      LeftAlt: LeftCtrl
keymap:
  - name: Konsole copy and paste and window management
    application:
      only: konsole org.kde.konsole
    remap:
      Shift-A: b
```

With this config, running with `RUST_LOG=debug`  I get:

```
[2024-03-24T15:03:38Z WARN  xremap::client::kde_client] Could not connect to kwin-script. Error: ClientSession
```
I did a little digging, and altered [kde_client.rs:100](https://github.com/xremap/xremap/blob/8dede9f0b169eb3f50f65487be7a9e5b5d846eb8/src/client/kde_client.rs#L100) from
```rust
let dbus = Connection::new_session().map_err(|_| ConnectionError::ClientSession)?;
``` 
to 
```rust
let dbus = Connection::new_session().map_err(|err| {warn!("err: {}", err); return ConnectionError::ClientSession;})?;
```
which gives a little more information:
```
Selecting devices from the following list:
------------------------------------------------------------------------------
/dev/input/event0 : AT Translated Set 2 keyboard
/dev/input/event1 : PC Speaker
/dev/input/event10: HDA Intel PCH HDMI/DP,pcm=3
/dev/input/event11: HDA Intel PCH HDMI/DP,pcm=7
/dev/input/event12: HDA Intel PCH HDMI/DP,pcm=8
/dev/input/event13: Synaptics TM3288-011
/dev/input/event14: TPPS/2 Elan TrackPoint
/dev/input/event2 : Video Bus
/dev/input/event3 : Sleep Button
/dev/input/event4 : Lid Switch
/dev/input/event5 : Power Button
/dev/input/event6 : ThinkPad Extra Buttons
/dev/input/event7 : HDA Digital PCBeep
/dev/input/event8 : HDA Intel PCH Mic
/dev/input/event9 : HDA Intel PCH Headphone
------------------------------------------------------------------------------
Selected keyboards automatically since --device options weren't specified:
------------------------------------------------------------------------------
/dev/input/event0 : AT Translated Set 2 keyboard
------------------------------------------------------------------------------
[2024-03-24T15:14:00Z DEBUG xremap::event_handler] => 0: KEY_ENTER
[2024-03-24T15:14:00Z DEBUG xremap::action_dispatcher] 0: KEY_ENTER
[2024-03-24T15:14:01Z DEBUG xremap::event_handler] => 1: KEY_LEFTSHIFT
[2024-03-24T15:14:01Z DEBUG xremap::action_dispatcher] 1: KEY_LEFTSHIFT
[2024-03-24T15:14:01Z DEBUG xremap::event_handler] => 1: KEY_A
[2024-03-24T15:14:01Z DEBUG xremap::client::kde_client] err: I/O error: No such file or directory (os error 2)
[2024-03-24T15:14:01Z WARN  xremap::client::kde_client] Could not connect to kwin-script. Error: ClientSession
application-client: KDE (supported: false)
[2024-03-24T15:14:01Z DEBUG xremap::action_dispatcher] 1: KEY_A
```
Disclaimer here, I'm not a rust programmer or knower of things D-Bus related (although I am digging into things to see if I can get a fix together). 

If anyone could give me any pointers on how I can gather some more info about the I/O error from zbus that would be awesome. I also noticed that xremap uses `zbus 1.9.3`, and the latest version is at `4.1.2` so I'm playing with updating to that, given that it seems to just be used in `kde_client.rs` and `gnome_client.rs`. Although there is a reasonable API change between those versions.

**Comment by N4tus** [comment]
Thank you for your detailed description, your log conforms that it is an issue with the connection to the session dbus. One way this can happen if xremap is run with root. If I try to run xremap as root on my system, i get the exact same error (i'm using debug formatting of the error but the error-kind is the same):
```
Io(
    Os {
        code: 2,
        kind: NotFound,
        message: "No such file or directory",
    },
)
```
There might be other ways an io error could occur (the docs of zbus aren't very detailed here). And if this is the case it's going to be more difficult to troubleshoot the issue.

If your are using systemd to start xremap, make sure to define the service as user-service (for example in `/etc/systemd/user/xremap.service`) and the start it with `systemctl --user start xremap`.

**Comment by dawsonalex** [comment]
Thanks! Looks like I'd missed the docs that say xremap can't be run as root :facepalm: I'll close this!
