### ISSUE TITLE
Can't detect any devices

### ISSUE THREAD

**Issue by Joevim** [xremap/xremap#456]
I'm new to this so you're gonna have to hold my hand.

I'm using fedora 39, kde plasma, wayland, on a dell laptop. xremap 0.8.18

When I type xremap ~/.config/xremap/config.yml I just get

```$ xremap ~/.config/xremap/config.yml
Selecting devices from the following list:
------------------------------------------------------------------------------
------------------------------------------------------------------------------
Selected keyboards automatically since --device options weren't specified:
------------------------------------------------------------------------------
```

but the /dev/input file isn't empty
```$ ls /dev/input
by-id    event0  event10  event12  event14  event3  event5  event7  event9  mouse0  mouse3
by-path  event1  event11  event13  event2   event4  event6  event8  mice    mouse2
```

**Comment by Joevim** [comment]
No, if I run with sudo it outputs

```sudo: xremap: command not found```

**Comment by k0kubun** [comment]
Could you specify a full path to xremap then?

**Comment by Joevim** [comment]
Thanks, it's working after I wrote the full path, ~/.config/xremap/config.yml wasn't working.
