### ISSUE TITLE
What is the name for XF86Back (keycode 166)?

### ISSUE THREAD

**Issue by Daviey** [xremap/xremap#464]
I'd like to achieve the xmodmap equivalent of  `keycode 166 = BackSpace` (keycode 166 is XF86Back), but I can't find it.  It would be helpful if there was a way of monitoring inputs, like `xev` to help generate a config.

Thanks

**Comment by k0kubun** [comment]
Running xremap with `RUST_LOG=debug xremap` gives you the key event names xremap recognizes, so please try that one. I want to have an option to do that instead of doing it through an environment variable, but please use that until somebody submits a patch for it.
