### ISSUE TITLE
allow multiple AUR packages

### ISSUE THREAD

**Issue by rikutons** [xremap/xremap#465]
I'm using multiple desktop env on 1 computer.
But `xremap-x11-bin` and `xremap-wlroots-bin` are conflicting at `/usr/bin/xremap` so I can't switch them easily.

`paru -S xremap-x11-bin` then `paru -S xremap-wlroots-bin` makes
```
error: failed to commit transaction (conflicting files)
xremap-wlroots-bin: /usr/bin/xremap exists in filesystem (owned by xremap-x11-bin)
Errors occurred, no packages were upgraded.
```

For example in case x11, can you make `xremap-x11-bin`'s binary name to `/usr/bin/xremap-x11` and create symlink to `/usr/bin/xremap` if `/usr/bin/xremap` is empty, or always override it to allow multiple xremap's packeges?

**Comment by k0kubun** [comment]
moved to https://github.com/xremap/aur-autoupdater/issues/49
