### ISSUE TITLE
If using an application specific remap, pressing a remapped key crashes xremap in hyprland 0.40.0

### ISSUE THREAD

**Issue by DJXJD** [xremap/xremap#477]
Here is the error message:
```
application-client: Hypr (supported: true)
thread 'main' panicked at /cargo/registry/src/index.crates.io-6f17d22bba15001f/hyprland-0.3.13/src/data/regular.rs:31:19:
A error occured while parsing the output from the hypr socket: IoError(Os { code: 2, kind: NotFound, message: "No such file or directory" })
```

**Comment by DJXJD** [comment]
Based on what I've seen, this issue should be able to be fixed by upgrading hyprland-rs to the 0.4.0 alpha, if that's something you want to do

**Comment by k0kubun** [comment]
Have you tried the `wlroots` binary? It should also work for Hyprland, and it's a more encouraged option since v0.8.9.

**Comment by DJXJD** [comment]
I believe I have, back when I first setup xremap. I'm using the AUR version, which as of now, is on 0.8.18. If I remember correctly, at the time, I wasn't able to get application specific remapping to work at all with the `wlroots` version. I'll give it another shot though and report back!

**Comment by DJXJD** [comment]
The `wlroots` version works beautifully! It also gives me access to window title based remapping, which, for my particular use case, is a lot nicer than window class based remapping.

Thank you so much for the help and for developing such an awesome project!

**Comment by k0kubun** [comment]
Nice! I fixed the AUR problem too.
